[package]
name = "coordinator-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.3", default-features = false, features = ["derive", "serde", "std"] } 
frostsnap_core = { path = "../frostsnap_core", features = ["std"] }
frostsnap_comms = { path = "../frostsnap_comms" }
schnorr_fun = { git = "https://github.com/llfourn/secp256kfun.git", rev = "51e2285be2433cdad7f0d6dc13e4b5f865cff34d", features = ["alloc"], default-features = false }
sha2 = "0.9"
rand = { version = "0.8" }
serde = { version = "1", features = ["derive"], default-features = false }
serde_json = "1.0.59"
thiserror = "1.0.21"
serialport = "4.2.0"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
home = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
nostr = "0.21.0"
hex = "0.4.3"
tungstenite = { version = "0.19", features = ["rustls-tls-webpki-roots"]}