[package]
name = "coordinator-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.2", default-features = false, features = ["alloc", "derive", "serde"] } 
frostsnap_core = { path = "../frostsnap_core" }
schnorr_fun = { git = "https://github.com/LLFourn/secp256kfun", rev = "a9a306bb2c76aff3d73bfad07087b0976737f71d", features = ["serde"] }
sha2 = "0.9"
rand = { version = "0.8" }
sled = "0.34.4"
sled-extensions = { version = "0.2.0", features = ["bincode"]}
serde = { version = "1", features = ["derive"], default-features = false }
serde_json = "1.0.59"
thiserror = "1.0.21"
serialport = "4.2.0"
