use super::{Column, Container, HoldToConfirm, Padding, Row, Text, Widget};
use crate::super_draw_target::SuperDrawTarget;
use crate::{palette::PALETTE, Instant, MainAxisAlignment};
use alloc::format;
use embedded_graphics::{
    draw_target::DrawTarget,
    geometry::{Point, Size},
    pixelcolor::Rgb565,
};
use u8g2_fonts::U8g2TextStyle;

type CodeText = Text<U8g2TextStyle<Rgb565>>;
type TofNText = Text<U8g2TextStyle<Rgb565>>;
type CodeColumn = Column<(TofNText, CodeText)>;
type PaddedCodeColumn = Padding<CodeColumn>;
type CodeContainer = Container<PaddedCodeColumn>;
type ConfirmText = Text<U8g2TextStyle<Rgb565>>;
type OnAllDevicesRow = Row<(ConfirmText, ConfirmText)>;
type PromptColumn = Column<(ConfirmText, CodeContainer, OnAllDevicesRow)>;

/// Widget for checking and confirming key generation
#[derive(frostsnap_macros::Widget)]
pub struct KeygenCheck {
    /// The hold-to-confirm widget
    #[widget_delegate]
    hold_to_confirm: HoldToConfirm<PromptColumn>,
}

impl KeygenCheck {
    /// Create a new keygen check widget
    pub fn new(t_of_n: (u16, u16), security_check_code: [u8; 4]) -> Self {
        // Format the t of n string
        let t_of_n_text = format!("{} of {}", t_of_n.0, t_of_n.1);

        // Format the security check code as hex
        let hex_code = format!(
            "{:02x}{:02x} {:02x}{:02x}",
            security_check_code[0],
            security_check_code[1],
            security_check_code[2],
            security_check_code[3]
        );

        // Create the t of n text widget
        let t_of_n_style = U8g2TextStyle::new(crate::FONT_MED, PALETTE.on_surface);
        let t_of_n_widget = Text::new(t_of_n_text.clone(), t_of_n_style.clone());

        // Create the hex code text widget using FONT_LARGE
        let code_style = U8g2TextStyle::new(crate::FONT_LARGE, PALETTE.on_surface);
        let code_widget = Text::new(hex_code.clone(), code_style);

        // Create internal column with t_of_n and code
        let code_column = Column::new((t_of_n_widget, code_widget));

        // Put the column in a container with a border
        let padded_code_column = Padding::all(10, code_column);
        let code_container = Container::new(padded_code_column)
            .with_border(PALETTE.outline, 2)
            .with_fill(PALETTE.surface)
            .with_corner_radius(Size::new(8, 8));

        // Create the "confirm identical" text
        let confirm_style = U8g2TextStyle::new(crate::FONT_MED, PALETTE.on_background);
        let confirm_identical_widget = Text::new("Confirm identical:", confirm_style.clone());

        // Create the "on all devices" text with underline
        let on_text = Text::new("on ", confirm_style.clone());
        let all_devices_text =
            Text::new("all devices", confirm_style).with_underline(PALETTE.on_background);

        let on_all_devices_row = Row::new((on_text, all_devices_text));

        // Create the prompt column with SpaceEvenly alignment
        let prompt_column =
            Column::new((confirm_identical_widget, code_container, on_all_devices_row))
                .with_main_axis_alignment(MainAxisAlignment::SpaceEvenly);

        // Create the hold-to-confirm widget
        let hold_to_confirm = HoldToConfirm::new(
            2000, // 2 second hold duration
            prompt_column,
        );

        Self { hold_to_confirm }
    }

    /// Check if the user has confirmed
    pub fn is_confirmed(&self) -> bool {
        self.hold_to_confirm.is_completed()
    }
}

// All trait implementations are now generated by the derive macro
