pub mod keygen_run;
pub mod remote_keygen;
pub mod remote_recovery;

use crate::api::broadcast::{BehaviorBroadcast, Broadcast};
use crate::frb_generated::{RustAutoOpaque, StreamSink};
use crate::nostr_settings_state::NostrSettingsState;
use anyhow::{anyhow, Result};
use flutter_rust_bridge::frb;
use frostsnap_coordinator::persist::Persisted;
use frostsnap_core::device::KeyPurpose;
use frostsnap_core::{
    coordinator::{KeyContext, ParticipantBinonces, ParticipantSignatureShares},
    message::EncodedSignature,
    AccessStructureId, AccessStructureRef, KeyId, SignSessionId, SymmetricKey, WireSignTask,
};
use frostsnap_macros::broadcast_handle;
pub use frostsnap_nostr::NostrProfile;
use frostsnap_nostr::{
    channel::{parse_frostsnap_link, parse_keygen_link},
    keygen::{LobbyChannelMetadata, LobbyClient},
    ChannelClient, ChannelHandle as InnerChannelHandle, ChannelInitData, ChannelKeys,
    ChannelRunner, Client, Keys, NostrDatabaseExt, NostrLMDB,
};
use rusqlite::Connection;
use std::{
    collections::HashMap,
    path::{Path, PathBuf},
    sync::{Arc, Mutex, OnceLock, RwLock},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Import-time public-kind-0 fetch timeout. Longer than the
/// runtime peer-fetch timeout (5 s) because this is a one-time
/// user-blocking operation and we'd rather wait than reject a
/// valid nsec on a flaky network.
const IMPORT_PROFILE_FETCH_TIMEOUT: Duration = Duration::from_secs(30);

pub use frostsnap_nostr::{
    ChannelEvent, ChannelParticipant, ChannelSecret, ConfirmedSubsetEntry, ConnectionState,
    EventId, GroupMember, ObservationKind, ParticipantShares, PublicKey, SigningEvent,
};

#[frb(opaque)]
pub struct ChannelConnectionParams {
    pub(crate) key_context: KeyContext,
    pub(crate) init_data: Option<ChannelInitData>,
}

static NOSTR_LMDB: OnceLock<Arc<NostrLMDB>> = OnceLock::new();

fn get_or_init_nostr_lmdb(data_dir: &Path) -> Arc<NostrLMDB> {
    NOSTR_LMDB
        .get_or_init(|| {
            let lmdb_path = data_dir.join("nostr-lmdb");
            let db = NostrLMDB::open(&lmdb_path).expect("failed to open nostr lmdb");
            Arc::new(db)
        })
        .clone()
}

fn get_nostr_lmdb() -> Result<Arc<NostrLMDB>> {
    NOSTR_LMDB
        .get()
        .cloned()
        .ok_or_else(|| anyhow!("nostr lmdb not initialized"))
}

// ============================================================================
// NostrSettings - Identity settings with reactive updates
// ============================================================================

/// FRB-translatable view of an access structure's local Nostr-coordination
/// settings. Carried directly by the per-access-structure broadcast so
/// fresh subscribers see current state without a separate sync read.
#[derive(Clone, Debug)]
pub struct AccessStructureSettings {
    pub key_id: KeyId,
    pub coordination_ui_enabled: bool,
}

impl AccessStructureSettings {
    fn default_for_ref(asref: AccessStructureRef) -> Self {
        Self {
            key_id: asref.key_id,
            coordination_ui_enabled: false,
        }
    }
}

broadcast_handle! { pub struct AccessStructureSettingsBcast(pub BehaviorBroadcast<AccessStructureSettings>); }

broadcast_handle! { pub struct ChannelEventBcast(pub Broadcast<ChannelEvent>); }

/// `Sink<ChannelEvent>` adapter that pushes events into the
/// per-channel `Broadcast<ChannelEvent>`. The signing wrapper
/// task in `frostsnap_nostr` writes through this; Dart consumers
/// register their `StreamSink`s on the same broadcast via the
/// leaf's `watch()` (generated by `broadcast_handle!`).
#[derive(Clone)]
struct BroadcastSink {
    bcast: Broadcast<ChannelEvent>,
}

impl frostsnap_coordinator::Sink<ChannelEvent> for BroadcastSink {
    fn send(&self, event: ChannelEvent) {
        self.bcast.add(&event);
    }
}

/// Nostr identity + per-access-structure coordination settings.
/// Mirrors the `Settings` pattern (`api/settings.rs`): a `Persisted<State>`
/// with a `Mutation` enum, plus the FRB-side stream sinks. Lives behind a
/// `RustAutoOpaque` on `AppCtx`, so `&mut self` setters are fine.
#[frb(opaque)]
pub struct NostrSettings {
    settings: Persisted<NostrSettingsState>,
    db: Arc<Mutex<Connection>>,

    /// Sink for identity updates. Emits the local pubkey; Dart computes
    /// npub on demand via `PublicKey.toNpub()`.
    identity_sink: Option<StreamSink<Option<PublicKey>>>,

    /// One `BehaviorBroadcast` per access structure. Lazily created on
    /// first subscribe (or pre-populated from `load`); each carries the
    /// latest `AccessStructureSettings` so newly-mounted UI sees the
    /// current state immediately. Multi-subscriber on the Rust side, no
    /// shared subject on the Dart side.
    coordination_broadcasts:
        RwLock<HashMap<AccessStructureId, BehaviorBroadcast<AccessStructureSettings>>>,
}

impl NostrSettings {
    /// Create by loading existing state from SQLite.
    /// Called during app initialization.
    pub(crate) fn new(db: Arc<Mutex<Connection>>, data_dir: PathBuf) -> Result<Self> {
        let settings: Persisted<NostrSettingsState> = {
            let mut conn = db.lock().unwrap();
            Persisted::new(&mut *conn, ())?
        };

        // Pre-populate one broadcast per loaded access structure so a fresh
        // subscriber sees the current state without waiting for a change
        // event.
        let coordination_broadcasts = RwLock::new(HashMap::new());
        {
            let mut map = coordination_broadcasts.write().unwrap();
            for (asid, settings) in &settings.access_structure_settings {
                map.insert(
                    *asid,
                    BehaviorBroadcast::seeded(AccessStructureSettings {
                        key_id: settings.key_id,
                        coordination_ui_enabled: settings.coordination_ui_enabled,
                    }),
                );
            }
        }

        // Initialize LMDB at the configured data dir.
        get_or_init_nostr_lmdb(&data_dir);

        Ok(Self {
            settings,
            db,
            identity_sink: None,
            coordination_broadcasts,
        })
    }

    /// Subscribe to identity changes. Emits current value immediately.
    /// Stream values are the local nostr pubkey; Dart computes the
    /// bech32 `npub` on demand via `PublicKey.toNpub()`.
    pub fn sub_identity(&mut self, sink: StreamSink<Option<PublicKey>>) -> Result<()> {
        self.identity_sink.replace(sink);
        self.emit_identity();
        Ok(())
    }

    /// Get a per-access-structure coordination settings leaf handle.
    /// Each `.watch().listen()` call attaches a fresh sink; the
    /// `BehaviorBroadcast` cached-emit guarantees the first event is
    /// the current `AccessStructureSettings` snapshot.
    #[frb(sync)]
    pub fn access_structure(
        &self,
        access_structure_ref: AccessStructureRef,
    ) -> AccessStructureSettingsBcast {
        AccessStructureSettingsBcast::new(self.broadcast_for(access_structure_ref))
    }

    /// Get-or-create the broadcast for an access structure, seeding the
    /// cached value with the latest persisted settings (or the default
    /// `coordination_ui_enabled = false` for an asref we've never seen).
    fn broadcast_for(
        &self,
        access_structure_ref: AccessStructureRef,
    ) -> BehaviorBroadcast<AccessStructureSettings> {
        let asid = access_structure_ref.access_structure_id;
        if let Some(b) = self.coordination_broadcasts.read().unwrap().get(&asid) {
            return b.clone();
        }
        let mut map = self.coordination_broadcasts.write().unwrap();
        // Re-check inside the write lock; another caller may have inserted.
        if let Some(b) = map.get(&asid) {
            return b.clone();
        }
        let initial = self
            .settings
            .access_structure_settings
            .get(&asid)
            .map(|s| AccessStructureSettings {
                key_id: s.key_id,
                coordination_ui_enabled: s.coordination_ui_enabled,
            })
            .unwrap_or_else(|| AccessStructureSettings::default_for_ref(access_structure_ref));
        let broadcast = BehaviorBroadcast::seeded(initial);
        map.insert(asid, broadcast.clone());
        broadcast
    }

    fn emit_identity(&self) {
        if let Some(sink) = &self.identity_sink {
            let _ = sink.add(self.settings.pubkey());
        }
    }

    fn emit_access_structure(&self, asref: AccessStructureRef) {
        let asid = asref.access_structure_id;
        let snapshot = self
            .settings
            .access_structure_settings
            .get(&asid)
            .map(|s| AccessStructureSettings {
                key_id: s.key_id,
                coordination_ui_enabled: s.coordination_ui_enabled,
            })
            .unwrap_or_else(|| AccessStructureSettings::default_for_ref(asref));
        self.broadcast_for(asref).add(&snapshot);
    }

    /// Get current identity pubkey synchronously.
    #[frb(sync)]
    pub fn current(&self) -> Option<PublicKey> {
        self.settings.pubkey()
    }

    /// Snapshot the current `NostrIdentity` (Mode A imported / Mode B
    /// generated) for the Dart layer to pattern-match on. `None` when
    /// no identity is configured.
    #[frb(sync)]
    pub fn current_identity(&self) -> Option<NostrIdentity> {
        self.settings.identity.clone()
    }

    /// Mode B — generate a fresh nsec and persist it as a `Generated`
    /// identity with the supplied display name. The name is captured
    /// here and immutable thereafter (renaming is out of scope for
    /// this revision). Returns the new nsec for export. Rejects an
    /// empty / whitespace-only name.
    pub fn generate_new_identity(&mut self, name: String) -> Result<String> {
        let trimmed = name.trim();
        if trimmed.is_empty() {
            return Err(anyhow!("display name must not be empty"));
        }
        let nsec = Nsec::generate();
        let nsec_str = nsec.0.clone();
        let identity = NostrIdentity::Generated {
            nsec,
            name: trimmed.to_string(),
            created_at: now_secs(),
        };
        let mut conn = self.db.lock().unwrap();
        self.settings.mutate2(&mut *conn, |st, update| {
            st.set_identity(Some(identity), update)
        })?;
        drop(conn);
        self.emit_identity();
        tracing::info!("generated new Nostr identity");
        Ok(nsec_str)
    }

    /// Mode A — store an imported nsec as an `Imported` identity with
    /// the supplied cached public profile. The caller (NostrClient)
    /// runs the public-kind-0 gate first.
    pub fn set_imported_identity(
        &mut self,
        nsec: String,
        cached_public_profile: Option<NostrProfile>,
    ) -> Result<()> {
        let nsec = Nsec::parse(nsec)?;
        let identity = NostrIdentity::Imported {
            nsec,
            cached_profile: cached_public_profile.unwrap_or_default(),
        };
        let mut conn = self.db.lock().unwrap();
        self.settings.mutate2(&mut *conn, |st, update| {
            st.set_identity(Some(identity), update)
        })?;
        drop(conn);
        self.emit_identity();
        tracing::info!("imported Nostr identity");
        Ok(())
    }

    /// Clear the identity (and its nsec) entirely.
    pub fn clear_identity(&mut self) -> Result<()> {
        let mut conn = self.db.lock().unwrap();
        self.settings
            .mutate2(&mut *conn, |st, update| st.set_identity(None, update))?;
        drop(conn);
        self.emit_identity();
        tracing::info!("Nostr identity cleared");
        Ok(())
    }

    /// Get nsec for export/backup. Returns an error if no identity is set.
    #[frb(sync)]
    pub fn get_nsec(&self) -> Result<String> {
        self.settings
            .identity
            .as_ref()
            .map(|id| match id {
                NostrIdentity::Imported { nsec, .. } | NostrIdentity::Generated { nsec, .. } => {
                    nsec.0.clone()
                }
            })
            .ok_or_else(|| anyhow!("no Nostr identity configured"))
    }

    /// Check if identity exists.
    #[frb(sync)]
    pub fn has_identity(&self) -> bool {
        self.settings.identity.is_some()
    }

    /// Whether the wallet behind this access structure should render its
    /// chat-first (remote-coordinated) UI shape.
    #[frb(sync)]
    pub fn is_coordination_ui_enabled(&self, access_structure_id: AccessStructureId) -> bool {
        self.settings
            .is_coordination_ui_enabled(access_structure_id)
    }

    pub fn set_coordination_ui_enabled(
        &mut self,
        access_structure_ref: AccessStructureRef,
        enabled: bool,
    ) -> Result<()> {
        let mut conn = self.db.lock().unwrap();
        self.settings.mutate2(&mut *conn, |st, update| {
            st.set_coordination_ui_enabled(access_structure_ref, enabled, update);
            Ok(())
        })?;
        drop(conn);
        self.emit_access_structure(access_structure_ref);
        Ok(())
    }
}

// ============================================================================
// ChannelHandle - per-consumer handle returned from connect_to_channel
// ============================================================================

/// Per-consumer handle for a connected channel. Owns its own
/// `ChannelRunner` + relay subscription + broadcast stream. The
/// caller (chat_page, post-keygen verify, etc.) holds this for the
/// lifetime of their session and calls `close()` to tear down.
///
/// Lifecycle is **two-phase** to avoid the lost-startup-events race
/// (codex feedback on commit 0ac5d35): `connect_to_channel` returns a
/// dormant handle; the caller attaches its `events().watch()`
/// listener, *then* awaits `start()`. The runner is spawned inside
/// `start()` — after the broadcast has subscribers — so the
/// `Connecting`/`Connected` emits and cache replay are observed.
///
/// FRB-opaque: send methods are callable on it directly, and
/// `events()` returns the non-opaque `ChannelEventBcast` leaf the
/// caller `watch()`es to get the event stream.
#[frb(opaque)]
pub struct ChannelHandle {
    bcast: Broadcast<ChannelEvent>,
    key_context: KeyContext,
    nostr_client: Client,
    identity: NostrIdentity,
    /// `Some(client)` until the first successful `start()` takes it.
    pending: tokio::sync::Mutex<Option<ChannelClient>>,
    /// Set once `start()` finishes its inner `ChannelClient::run`.
    inner: tokio::sync::OnceCell<InnerChannelHandle>,
}

impl ChannelHandle {
    /// Return the broadcast leaf. Dart calls `events().watch()` to
    /// get the live `Stream<ChannelEvent>`. Each call mints a fresh
    /// leaf wrapping an Arc-clone of the same underlying broadcast,
    /// so multiple `watch()` calls all see the same events.
    #[frb(sync)]
    pub fn events(&self) -> ChannelEventBcast {
        ChannelEventBcast::new(self.bcast.clone())
    }

    /// Spawn the per-channel runner and begin emitting into the
    /// broadcast. **Must be awaited after** at least one listener has
    /// been attached via `events().watch().listen(...)`, otherwise
    /// `Connecting`/`Connected` and cache-replay events emitted during
    /// startup will be dropped on the floor.
    ///
    /// Idempotent: second and later calls return `Ok(())` immediately.
    pub async fn start(&self) -> Result<()> {
        if self.inner.initialized() {
            return Ok(());
        }
        let mut pending = self.pending.lock().await;
        if self.inner.initialized() {
            return Ok(());
        }
        let cc = pending
            .take()
            .ok_or_else(|| anyhow!("channel handle has no pending client"))?;
        let sink = BroadcastSink {
            bcast: self.bcast.clone(),
        };
        let inner = cc
            .run(self.nostr_client.clone(), sink, self.identity.clone())
            .await
            .map_err(|e| {
                tracing::error!(error = %e, "failed to start channel runner");
                e
            })?;
        // Publish-after-fold is handled inside ChannelRunner::run via
        // the identity's publish policy; no explicit call here.
        let _ = self.inner.set(inner);
        Ok(())
    }

    fn require_inner(&self) -> Result<&InnerChannelHandle> {
        self.inner
            .get()
            .ok_or_else(|| anyhow!("channel handle not started — call start() first"))
    }

    /// Send a chat message. `reply_to` is optional. Signs with the
    /// identity captured at `connect_to_channel` time — see
    /// [`NostrClient::connect_to_channel`].
    pub async fn send_message(
        &self,
        content: String,
        reply_to: Option<EventId>,
    ) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        inner.send_message(content, reply_to, &keys).await
    }

    /// Share a receive address in the channel.
    pub async fn send_receive_address(
        &self,
        derivation_index: u32,
        memo: String,
    ) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        inner
            .send_receive_address(&keys, derivation_index, memo)
            .await
    }

    /// Propose a transaction for signing.
    pub async fn send_sign_request(
        &self,
        unsigned_tx: super::signing::UnsignedTx,
        message: String,
    ) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        let sign_task = WireSignTask::BitcoinTransaction(unsigned_tx.template_tx.clone());
        inner.send_sign_request(&keys, sign_task, message).await
    }

    /// Propose a test message for signing.
    pub async fn send_test_sign_request(
        &self,
        test_message: String,
        message: String,
    ) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        let sign_task = WireSignTask::Test {
            message: test_message,
        };
        inner.send_sign_request(&keys, sign_task, message).await
    }

    pub async fn send_sign_offer(
        &self,
        request_id: EventId,
        binonces: Vec<ParticipantBinonces>,
    ) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        inner.send_sign_offer(&keys, request_id, binonces).await
    }

    pub async fn send_sign_partial(
        &self,
        request_id: EventId,
        offer_subset: Vec<EventId>,
        shares: frostsnap_core::coordinator::ParticipantSignatureShares,
    ) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        inner
            .send_sign_partial(&keys, request_id, offer_subset, shares)
            .await
    }

    pub async fn send_sign_cancel(&self, request_id: EventId) -> Result<EventId> {
        let inner = self.require_inner()?;
        let keys = inner.runner_handle.signing_keys().clone();
        inner.send_sign_cancel(&keys, request_id).await
    }

    /// Pump a wallet-stream tx into the channel runner so it can fold
    /// chat→tx correlations.
    pub async fn notify_tx_observed(&self, tx: crate::api::bitcoin::Transaction) -> Result<()> {
        let wallet_tx = frostsnap_coordinator::bitcoin::wallet::Transaction {
            inner: std::sync::Arc::new(tx.inner.clone()),
            txid: tx.inner.compute_txid(),
            confirmation_time: tx.confirmation_time.clone(),
            first_seen: tx.first_seen,
            last_seen: tx.last_seen,
            prevouts: tx.prevouts.clone(),
            is_mine: tx.is_mine.clone(),
        };
        self.require_inner()?.notify_tx_observed(wallet_tx).await
    }

    /// Build a `SealedSigningData` bundle when Dart receives a
    /// `SigningEvent::RoundConfirmed`. Uses the channel's
    /// `KeyContext` captured at connect time.
    #[frb(sync)]
    pub fn seal_round_confirmed(
        &self,
        request_id: EventId,
        sign_task: WireSignTask,
        binonces: Vec<ParticipantBinonces>,
    ) -> Result<SealedSigningData> {
        Ok(SealedSigningData {
            request_id: request_id.into(),
            sign_task,
            binonces,
            key_context: self.key_context.clone(),
        })
    }

    /// Signal the runner to shut down. Returns immediately
    /// (fire-and-forget). No-op if `start()` was never called
    /// (nothing to tear down yet). Call from Flutter `State.dispose()`
    /// since dispose can't be `async`. Forget to call it and the
    /// runner leaks to process exit — the caller owns the handle.
    #[frb(sync)]
    pub fn close(&self) {
        if let Some(inner) = self.inner.get() {
            inner.runner_handle.shutdown();
        }
    }
}

// ============================================================================
// NostrClient - Unified client for profiles and channels
// ============================================================================

/// Unified Nostr client for profiles and channels.
/// Create once and keep around - cloning shares the connection pool.
pub struct NostrClient {
    client: Client,
}

impl NostrClient {
    /// Connect to default relays and return a client ready for use.
    pub async fn connect() -> Result<Self> {
        let database = get_nostr_lmdb()?;
        let client = Client::builder().database(database).build();

        for url in default_relay_urls() {
            if let Err(e) = client.add_relay(&url).await {
                tracing::warn!(relay = %url, error = %e, "failed to add relay");
            }
        }

        client.connect().await;

        Ok(Self { client })
    }

    /// Fetch profile metadata for a public key.
    /// Checks the local cache first, then fetches from relays if not found.
    /// Returns None if the user has no profile.
    pub async fn fetch_profile(&self, pubkey: &PublicKey) -> Result<Option<NostrProfile>> {
        self.fetch_profile_with_timeout(pubkey, Duration::from_secs(5))
            .await
    }

    async fn fetch_profile_with_timeout(
        &self,
        pubkey: &PublicKey,
        timeout: Duration,
    ) -> Result<Option<NostrProfile>> {
        let nostr_pk = (*pubkey).into();
        if let Ok(Some(metadata)) = self.client.database().metadata(nostr_pk).await {
            return Ok(Some(NostrProfile::from_metadata(*pubkey, metadata)));
        }
        match self.client.fetch_metadata(nostr_pk, timeout).await {
            Ok(Some(metadata)) => Ok(Some(NostrProfile::from_metadata(*pubkey, metadata))),
            Ok(None) => Ok(None),
            Err(e) => {
                tracing::debug!(pubkey = %pubkey, error = %e, "failed to fetch profile");
                Ok(None)
            }
        }
    }

    /// Mode A — validate that an imported nsec has a discoverable
    /// public NIP-01 kind 0, and return the fetched profile. Used by
    /// the Dart layer's Import button before calling
    /// `NostrSettings::set_imported_identity`. 30-second timeout
    /// because this is a one-time user-blocking operation.
    pub async fn fetch_profile_for_import(&self, nsec: String) -> Result<NostrProfile> {
        let keys = Keys::parse(&nsec)?;
        let pubkey: PublicKey = keys.public_key().into();
        match self
            .fetch_profile_with_timeout(&pubkey, IMPORT_PROFILE_FETCH_TIMEOUT)
            .await?
        {
            Some(profile) => Ok(profile),
            None => Err(anyhow!(
                "No public profile found for this nsec. \
                 Set one up in your usual nostr client \
                 (publish a kind 0 metadata event), then try importing again."
            )),
        }
    }

    /// Build a fresh per-consumer `ChannelHandle`. The handle is
    /// returned dormant — the runner is only spawned when the caller
    /// awaits `handle.start()`. This split lets Dart attach its
    /// `events().watch().listen(...)` listener *before* the runner
    /// emits `Connecting`, `Connected`, and the cache replay, so no
    /// startup events are dropped.
    ///
    /// No `StreamSink` param — FRB can't have a function that BOTH
    /// returns a value and exposes a Dart `Stream`. The Dart side
    /// gets the event stream via `handle.events().watch()`.
    pub async fn connect_to_channel(
        &self,
        identity: NostrIdentity,
        params: &ChannelConnectionParams,
    ) -> Result<ChannelHandle> {
        let key_context = params.key_context.clone();
        let channel_client =
            ChannelClient::new(params.key_context.clone(), params.init_data.clone());

        Ok(ChannelHandle {
            bcast: Broadcast::<ChannelEvent>::default(),
            key_context,
            nostr_client: self.client.clone(),
            identity,
            pending: tokio::sync::Mutex::new(Some(channel_client)),
            inner: tokio::sync::OnceCell::new(),
        })
    }

    /// Join a wallet from a nostr invite link. Fetches channel data from relays,
    /// adds the key to the coordinator, and returns the new wallet's KeyId.
    pub async fn join_from_link(
        &self,
        coord: &super::coordinator::Coordinator,
        channel_secret: ChannelSecret,
        encryption_key: SymmetricKey,
    ) -> Result<frostsnap_core::KeyId> {
        let channel_keys = ChannelKeys::from_channel_secret(&channel_secret);
        let runner = ChannelRunner::new(channel_keys.clone());
        let init_event = runner
            .fetch_init_event(&self.client)
            .await?
            .ok_or_else(|| anyhow!("no channel found for this link"))?;
        let init_data =
            frostsnap_nostr::channel_runner::decode_bincode::<ChannelInitData>(&init_event)?;

        let derived_channel_keys =
            ChannelKeys::from_access_structure_id(&init_data.access_structure_id());
        anyhow::ensure!(
            derived_channel_keys == channel_keys,
            "channel secret mismatch in channel init data"
        );

        let as_ref = {
            let mut db = coord.0.db.lock().unwrap();
            let mut coordinator = coord.0.coordinator.lock().unwrap();
            coordinator.staged_mutate(&mut *db, |coordinator| {
                Ok(coordinator.add_key_and_access_structure(
                    init_data.key_name.clone(),
                    init_data.root_shared_key.clone(),
                    init_data.purpose,
                    encryption_key,
                    &mut rand::thread_rng(),
                ))
            })?
        };

        coord.0.emit_key_state();
        Ok(as_ref.key_id)
    }

    /// Open a remote keygen lobby at `channel_secret` as the initiator.
    /// Publishes the nostr `ChannelCreation` event — with the wallet
    /// name + purpose carried inline in its content — and returns a
    /// handle the caller uses to register devices or cancel.
    pub async fn create_remote_lobby(
        &self,
        identity: NostrIdentity,
        channel_secret: ChannelSecret,
        key_name: String,
        purpose: KeyPurpose,
    ) -> Result<self::remote_keygen::RemoteLobbyHandle> {
        let keys = identity.keys()?;
        let lobby_client = LobbyClient::new(channel_secret.clone());
        let invite_link = channel_secret.keygen_invite_link();
        let metadata = LobbyChannelMetadata { key_name, purpose };
        let init_event = lobby_client.build_creation_event(&keys, &metadata).await?;
        let (bridge, sink) = self::remote_keygen::RemoteLobbyHandle::build_bridge();
        let handle = lobby_client
            .run(self.client.clone(), identity, Some(init_event), sink)
            .await?;
        Ok(self::remote_keygen::RemoteLobbyHandle::new(
            handle,
            keys,
            invite_link,
            self.client.clone(),
            bridge,
        ))
    }

    /// Join an existing remote keygen lobby. `channel_secret` comes from
    /// parsing the initiator's `frostsnap://channel/…` invite link
    /// (see `ChannelSecret::from_invite_link`).
    pub async fn join_remote_lobby(
        &self,
        identity: NostrIdentity,
        channel_secret: ChannelSecret,
    ) -> Result<self::remote_keygen::RemoteLobbyHandle> {
        let keys = identity.keys()?;
        let lobby_client = LobbyClient::new(channel_secret.clone());
        let invite_link = channel_secret.keygen_invite_link();
        let (bridge, sink) = self::remote_keygen::RemoteLobbyHandle::build_bridge();
        let handle = lobby_client
            .run(self.client.clone(), identity, None, sink)
            .await?;
        Ok(self::remote_keygen::RemoteLobbyHandle::new(
            handle,
            keys,
            invite_link,
            self.client.clone(),
            bridge,
        ))
    }

    /// Leader entry: creates a remote recovery lobby, publishes the
    /// NIP-28 `ChannelCreation` with encoded metadata, and returns a
    /// handle whose `invite_link()` is what the leader shares with
    /// joiners.
    pub async fn create_remote_recovery_lobby(
        &self,
        identity: NostrIdentity,
        channel_secret: ChannelSecret,
        key_name: String,
        purpose: KeyPurpose,
        threshold_hint: Option<u16>,
    ) -> Result<self::remote_recovery::RemoteRecoveryLobbyHandle> {
        use self::remote_recovery::{RecoveryBridge, RemoteRecoveryLobbyHandle};
        use frostsnap_nostr::recovery::{RecoveryChannelMetadata, RecoveryLobbyClient};

        let metadata = RecoveryChannelMetadata {
            key_name,
            purpose,
            threshold_hint,
        };
        let client = RecoveryLobbyClient::new(channel_secret.clone()).with_metadata(metadata);
        let invite_link = client.invite_link();
        let init_event = client.build_creation_event(&identity).await?;
        let bridge = RecoveryBridge::new();
        let sink = bridge.sink();
        let inner = client
            .run(self.client.clone(), identity, Some(init_event), sink)
            .await?;

        // Leader: broadcast can't seed synchronously because the ChannelCreation
        // hasn't been folded yet at this instant. Await the sink's first
        // StateChanged (matches the joiner arm-then-check pattern for symmetry
        // and gives the same guarantee: the handed-out handle carries a
        // populated broadcast).
        let broadcast = await_first_state(&bridge).await?;
        Ok(RemoteRecoveryLobbyHandle::from_bridge(
            inner,
            invite_link,
            self.client.clone(),
            broadcast,
            &bridge,
        ))
    }

    /// Joiner entry: awaits the leader's `ChannelCreation` (30s timeout)
    /// so the returned handle carries a broadcast seeded with real
    /// metadata.
    pub async fn join_remote_recovery_lobby(
        &self,
        identity: NostrIdentity,
        channel_secret: ChannelSecret,
    ) -> Result<self::remote_recovery::RemoteRecoveryLobbyHandle> {
        use self::remote_recovery::{RecoveryBridge, RemoteRecoveryLobbyHandle};
        use frostsnap_nostr::recovery::RecoveryLobbyClient;

        let client = RecoveryLobbyClient::new(channel_secret.clone());
        let invite_link = client.invite_link();
        let bridge = RecoveryBridge::new();
        let sink = bridge.sink();
        let inner = client
            .run(self.client.clone(), identity, None, sink)
            .await?;

        let broadcast = await_first_state(&bridge).await?;
        Ok(RemoteRecoveryLobbyHandle::from_bridge(
            inner,
            invite_link,
            self.client.clone(),
            broadcast,
            &bridge,
        ))
    }
}

/// Arm-then-check wait pattern: poll the shared broadcast slot,
/// arming the Notify's `notified()` before each read so a
/// concurrently-firing `notify_waiters` isn't missed. See plan
/// §"Emission gate" for the rationale.
async fn await_first_state(
    bridge: &self::remote_recovery::RecoveryBridge,
) -> Result<BehaviorBroadcast<frostsnap_nostr::recovery::RecoveryLobbySnapshot>> {
    tokio::time::timeout(std::time::Duration::from_secs(30), async {
        loop {
            let notified = bridge.ready.notified();
            tokio::pin!(notified);
            notified.as_mut().enable();

            if *bridge.cancelled_pre_state.lock().unwrap() {
                return Err(anyhow!(
                    "recovery channel malformed — metadata decode failed"
                ));
            }
            if let Some(bcast) = bridge.broadcast.lock().unwrap().as_ref().cloned() {
                return Ok(bcast);
            }
            notified.await;
        }
    })
    .await
    .map_err(|_| anyhow!("ChannelCreation didn't arrive within 30s"))?
}

// ============================================================================
// Nsec - Our newtype wrapper for Nostr secret keys
// ============================================================================

pub use frostsnap_nostr::{NostrIdentity, Nsec};

/// FRB mirror for `frostsnap_nostr::Nsec` (moved out of this crate;
/// see the `nostr_identity_type` plan). The methods are re-exposed
/// via `#[frb(external)]` below.
#[frb(mirror(Nsec), non_opaque)]
pub struct _Nsec(pub String);

#[frb(external)]
impl Nsec {
    #[frb(sync)]
    pub fn generate() -> Self {}

    #[frb(sync)]
    pub fn parse(_s: String) -> Result<Self> {}
}

/// FRB mirror for `frostsnap_nostr::NostrIdentity`. Non-opaque
/// so Dart can construct + pattern-match on the variant. All
/// fields are FRB-safe (Nsec, NostrProfile, String, u64).
#[frb(mirror(NostrIdentity), non_opaque)]
pub enum _NostrIdentity {
    Imported {
        nsec: Nsec,
        cached_profile: NostrProfile,
    },
    Generated {
        nsec: Nsec,
        name: String,
        created_at: u64,
    },
}

/// Dart-visible pubkey accessor on `NostrIdentity`. Signing keys
/// stay Rust-internal; Dart only needs the pubkey for display. Sync
/// getter — unwraps the Nsec parse since it was validated at
/// construction time.
#[frb(sync)]
pub fn identity_pubkey(identity: &NostrIdentity) -> PublicKey {
    identity
        .public_key()
        .expect("nsec must be valid — was validated at Nsec::parse time")
}

// ============================================================================
// PublicKey - Value mirror (32 bytes, x-only)
// ============================================================================

#[frb(mirror(ChannelSecret))]
pub struct _ChannelSecret(pub [u8; 16]);

#[frb(external)]
impl ChannelSecret {
    #[frb(sync)]
    pub fn from_access_structure_id(_id: &AccessStructureId) -> Self {}

    /// `frostsnap://channel/<hex>` — post-keygen wallet channel invite.
    #[frb(sync)]
    pub fn invite_link(&self) -> String {}

    /// `frostsnap://keygen/<hex>` — visually distinct scheme used for
    /// remote keygen lobby invites so the receiver UI can route to the
    /// lobby-join flow rather than the already-completed-wallet flow.
    #[frb(sync)]
    pub fn keygen_invite_link(&self) -> String {}

    /// `frostsnap://recovery/<hex>` — visually distinct scheme used
    /// for remote recovery lobby invites so the receiver UI can
    /// route to the recovery-join flow.
    #[frb(sync)]
    pub fn recovery_invite_link(&self) -> String {}
}

pub trait ChannelSecretExt {
    #[frb(sync)]
    fn from_invite_link(link: &str) -> Result<ChannelSecret>;

    #[frb(sync)]
    fn from_keygen_link(link: &str) -> Result<ChannelSecret>;

    #[frb(sync)]
    fn from_recovery_link(link: &str) -> Result<ChannelSecret>;

    /// Generate a fresh random `ChannelSecret`. Named `generate` to avoid
    /// colliding with the native `ChannelSecret::random(rng)` (which Dart
    /// can't call since it needs an RNG argument).
    #[frb(sync)]
    fn generate() -> ChannelSecret;
}

impl ChannelSecretExt for ChannelSecret {
    #[frb(sync)]
    fn from_invite_link(link: &str) -> Result<ChannelSecret> {
        parse_frostsnap_link(link).map_err(|e| anyhow!("{e}"))
    }

    #[frb(sync)]
    fn from_keygen_link(link: &str) -> Result<ChannelSecret> {
        parse_keygen_link(link).map_err(|e| anyhow!("{e}"))
    }

    #[frb(sync)]
    fn from_recovery_link(link: &str) -> Result<ChannelSecret> {
        frostsnap_nostr::channel::parse_recovery_link(link).map_err(|e| anyhow!("{e}"))
    }

    #[frb(sync)]
    fn generate() -> ChannelSecret {
        ChannelSecret::random(&mut rand::thread_rng())
    }
}

/// Mirrors `frostsnap_nostr::PublicKey`. Same `dart_code` override as
/// `EventId` — content-equality `==` / `hashCode` so `PublicKey` works
/// as a `Map` key on the Dart side.
#[frb(
    mirror(PublicKey),
    non_opaque,
    non_hash,
    non_eq,
    dart_code = "
  @override
  int get hashCode => Object.hashAll(field0);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is PublicKey && _listEquals(field0, other.field0));

  static bool _listEquals(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    for (int i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
"
)]
pub struct _PublicKey(pub [u8; 32]);

#[frb(external)]
impl PublicKey {
    #[frb(sync)]
    pub fn to_hex(&self) -> String {}

    #[frb(sync)]
    pub fn to_npub(&self) -> String {}
}

// ============================================================================
// EventId mirror — value-typed, 32 bytes. Mirrors `frostsnap_nostr::EventId`.
// ============================================================================

/// Mirrors `frostsnap_nostr::EventId`. Custom dart_code overrides
/// `==` and `hashCode` to compare by content (so `EventId` works as a
/// `Map` key in Dart), since the auto-generated tuple-struct equality
/// would compare by reference.
#[frb(
    mirror(EventId),
    non_opaque,
    non_hash,
    non_eq,
    dart_code = "
  @override
  int get hashCode => Object.hashAll(field0);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is EventId && _listEquals(field0, other.field0));

  static bool _listEquals(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    for (int i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
"
)]
pub struct _EventId(pub [u8; 32]);

#[frb(external)]
impl EventId {
    #[frb(sync)]
    pub fn to_hex(&self) -> String {}
}

/// A member of the channel group with their profile. Mirrors
/// `frostsnap_nostr::GroupMember`.
#[frb(mirror(GroupMember), non_opaque)]
pub struct _GroupMember {
    pub pubkey: PublicKey,
    pub profile: Option<NostrProfile>,
}

/// Mirrors `frostsnap_nostr::ConnectionState`.
#[frb(mirror(ConnectionState), non_opaque)]
pub enum _ConnectionState {
    Connecting,
    Connected,
    Disconnected { reason: Option<String> },
}

/// Mirrors `frostsnap_nostr::ObservationKind`.
#[frb(mirror(ObservationKind), non_opaque)]
pub enum _ObservationKind {
    Mempool,
    Confirmed,
}

/// Mirrors `frostsnap_nostr::signing::ConfirmedSubsetEntry` — one entry
/// in `SigningEvent::RoundConfirmed.subset`.
#[frb(mirror(ConfirmedSubsetEntry), non_opaque)]
pub struct _ConfirmedSubsetEntry {
    pub event_id: EventId,
    pub author: PublicKey,
    pub timestamp: u64,
    pub binonces: Vec<ParticipantBinonces>,
}

/// Mirrors `frostsnap_nostr::SigningEvent`. Variants stay 1:1 with the
/// source; the previously-embedded `signing_details` (Request) and
/// `share_indices` (Offer) projections are now Dart-callable helpers
/// (see `signing_details`, `offer_share_indices` below). The
/// `RoundConfirmed.sealed` opaque bundle is built on demand via
/// `ChannelHandle::seal_round_confirmed(...)`.
#[frb(mirror(SigningEvent), non_opaque)]
pub enum _SigningEvent {
    Request {
        event_id: EventId,
        author: PublicKey,
        sign_task: WireSignTask,
        message: String,
        timestamp: u64,
    },
    Offer {
        event_id: EventId,
        author: PublicKey,
        request_id: EventId,
        binonces: Vec<ParticipantBinonces>,
        timestamp: u64,
    },
    RoundConfirmed {
        request_id: EventId,
        subset: Vec<ConfirmedSubsetEntry>,
        session_id: SignSessionId,
        sign_task: WireSignTask,
        timestamp: u64,
    },
    RoundPending {
        request_id: EventId,
        observed: Vec<EventId>,
        threshold: usize,
        timestamp: u64,
    },
    Partial {
        event_id: EventId,
        author: PublicKey,
        request_id: EventId,
        offer_subset: Vec<EventId>,
        session_id: SignSessionId,
        signature_shares: ParticipantSignatureShares,
        timestamp: u64,
    },
    Cancel {
        event_id: EventId,
        author: PublicKey,
        request_id: EventId,
        timestamp: u64,
    },
    Rejected {
        event_id: EventId,
        author: PublicKey,
        timestamp: u64,
        reason: String,
    },
}

/// Mirrors `frostsnap_nostr::ChannelEvent`. The previous bespoke
/// `FfiChannelEvent` is gone — variants flow through unchanged.
#[frb(mirror(ChannelEvent), non_opaque)]
pub enum _ChannelEvent {
    ChatMessage {
        message_id: EventId,
        author: PublicKey,
        content: String,
        timestamp: u64,
        reply_to: Option<EventId>,
        pending: bool,
    },
    MessageSent {
        message_id: EventId,
    },
    MessageSendFailed {
        message_id: EventId,
        reason: String,
    },
    ReceiveAddress {
        message_id: EventId,
        author: PublicKey,
        timestamp: u64,
        pending: bool,
        derivation_index: u32,
        memo: String,
    },
    ReceiveAddressSendFailed {
        message_id: EventId,
        reason: String,
    },
    TxObservation {
        txid: String,
        kind: ObservationKind,
        timestamp: u64,
        address_reveal_event: Option<EventId>,
        signing_start_event: Option<EventId>,
    },
    ConnectionState(ConnectionState),
    GroupMetadata {
        members: Vec<GroupMember>,
    },
    Signing {
        event: SigningEvent,
        pending: bool,
    },
    Error {
        event_id: EventId,
        author: PublicKey,
        timestamp: u64,
        reason: String,
    },
    ChannelState {
        participants: Vec<ChannelParticipant>,
    },
}

#[frb(mirror(ChannelParticipant), non_opaque)]
pub struct _ChannelParticipant {
    pub pubkey: PublicKey,
    pub share_indices: Vec<u32>,
}

/// Compute the UI-shape `SigningDetails` for a sign task. Dart calls
/// this on demand; the field used to ride embedded on
/// `SigningEvent::Request` but it's just a derivation of the task.
#[frb(sync)]
pub fn signing_details(sign_task: &WireSignTask) -> super::signing::SigningDetails {
    use super::signing::WireSignTaskExt;
    sign_task.signing_details()
}

/// Compute the per-binonce share indices, the UI-friendly projection
/// of `SigningEvent::Offer.binonces`. Dart calls this on demand; the
/// field used to ride embedded on the variant.
#[frb(sync)]
pub fn offer_share_indices(binonces: &[ParticipantBinonces]) -> Vec<u32> {
    binonces
        .iter()
        .map(|b| u32::try_from(b.share_index).expect("share index fits in u32"))
        .collect()
}

/// Opaque bundle of round data needed to combine signatures standalone.
/// Built on demand by `ChannelHandle::seal_round_confirmed(...)` when a
/// `SigningEvent::RoundConfirmed` lands, since it carries the channel's
/// `key_context` (which isn't on the source `SigningEvent` itself).
#[frb(opaque)]
#[derive(Debug, Clone)]
pub struct SealedSigningData {
    pub(crate) request_id: frostsnap_nostr::EventId,
    pub(crate) sign_task: WireSignTask,
    pub(crate) binonces: Vec<ParticipantBinonces>,
    pub(crate) key_context: KeyContext,
}

impl SealedSigningData {
    #[frb(sync)]
    pub fn sign_task(&self) -> WireSignTask {
        self.sign_task.clone()
    }

    #[frb(sync)]
    pub fn access_structure_ref(&self) -> AccessStructureRef {
        self.key_context.access_structure_ref()
    }

    #[frb(sync)]
    pub fn binonces(&self) -> Vec<ParticipantBinonces> {
        self.binonces.clone()
    }

    #[frb(sync)]
    pub fn sign_session_id(&self) -> SignSessionId {
        use frostsnap_core::message::GroupSignReq;
        GroupSignReq::from_binonces(
            self.sign_task.clone(),
            self.key_context.access_structure_id(),
            &self.binonces,
        )
        .session_id()
    }

    #[frb(sync)]
    pub fn combine_signatures(
        &self,
        all_shares: Vec<RustAutoOpaque<ParticipantSignatureShares>>,
    ) -> anyhow::Result<Vec<EncodedSignature>> {
        let guards: Vec<_> = all_shares
            .iter()
            .map(|s: &RustAutoOpaque<ParticipantSignatureShares>| s.blocking_read())
            .collect();
        let share_refs: Vec<&ParticipantSignatureShares> = guards.iter().map(|g| &**g).collect();
        Ok(frostsnap_core::coordinator::signing::combine_signatures(
            self.sign_task.clone(),
            &self.key_context,
            &self.binonces,
            &share_refs,
        )?)
    }
}

/// `Sink<ChannelEvent>` that forwards the source enum directly to a
/// `StreamSink<ChannelEvent>` — no per-event conversion. The
/// `SealedSigningData` bundle that used to ride embedded on
/// `RoundConfirmed` is now built on demand via
/// `ChannelHandle::seal_round_confirmed(...)`, which already has the
/// channel's `key_context`.

/// Nostr profile metadata (NIP-01 kind 0). Mirrors `frostsnap_nostr::NostrProfile`.
#[frb(mirror(NostrProfile), non_opaque)]
pub struct _NostrProfile {
    pub pubkey: Option<PublicKey>,
    pub name: Option<String>,
    pub display_name: Option<String>,
    pub about: Option<String>,
    pub picture: Option<String>,
    pub banner: Option<String>,
    pub nip05: Option<String>,
    pub website: Option<String>,
}

/// Get default relay URLs (public relays for profile/event discovery).
#[frb(sync)]
pub fn default_relay_urls() -> Vec<String> {
    vec![
        "wss://relay.damus.io".to_string(),
        "wss://nos.lol".to_string(),
        "wss://relay.primal.net".to_string(),
    ]
}
