name: "Build macOS App"
description: "Builds macOS app and creates DMG"

inputs:
  firmware_path:
    description: "Path to firmware.bin file"
    required: true

runs:
  using: "composite"
  steps:
    - uses: "./.github/actions/set-up-app-build"
      with:
        firmware_path: ${{ inputs.firmware_path }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin
    - uses: "./.github/actions/cache-rust-target"
      with:
        key: "app-build-macos-v0"
        path: |
          target/aarch64-apple-darwin/release
          target/x86_64-apple-darwin/release
    - name: Install CocoaPods
      shell: bash
      run: gem install cocoapods
    - name: Install create-dmg
      shell: bash
      run: brew install create-dmg
    - name: Build App macOS and Create DMG
      shell: bash
      run: just build-dmg
