// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';

class NativePlatform extends FlutterRustBridgeBase<NativeWire>
    with FlutterRustBridgeSetupMixin {
  NativePlatform(FutureOr<WasmModule> dylib) : super(NativeWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  Object api2wire_FfiCoordinator(FfiCoordinator raw) {
    return raw.shareOrMove();
  }

  @protected
  Object api2wire_PortBytesToReadSender(PortBytesToReadSender raw) {
    return raw.shareOrMove();
  }

  @protected
  Object api2wire_PortOpenSender(PortOpenSender raw) {
    return raw.shareOrMove();
  }

  @protected
  Object api2wire_PortReadSender(PortReadSender raw) {
    return raw.shareOrMove();
  }

  @protected
  Object api2wire_PortWriteSender(PortWriteSender raw) {
    return raw.shareOrMove();
  }

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  List<dynamic> api2wire_box_autoadd_device_id(DeviceId raw) {
    return api2wire_device_id(raw);
  }

  @protected
  List<dynamic> api2wire_box_autoadd_port_bytes_to_read(PortBytesToRead raw) {
    return api2wire_port_bytes_to_read(raw);
  }

  @protected
  List<dynamic> api2wire_box_autoadd_port_open(PortOpen raw) {
    return api2wire_port_open(raw);
  }

  @protected
  List<dynamic> api2wire_box_autoadd_port_read(PortRead raw) {
    return api2wire_port_read(raw);
  }

  @protected
  List<dynamic> api2wire_box_autoadd_port_write(PortWrite raw) {
    return api2wire_port_write(raw);
  }

  @protected
  List<dynamic> api2wire_device_id(DeviceId raw) {
    return [api2wire_u8_array_33(raw.field0)];
  }

  @protected
  List<dynamic> api2wire_list_port_desc(List<PortDesc> raw) {
    return raw.map(api2wire_port_desc).toList();
  }

  @protected
  String? api2wire_opt_String(String? raw) {
    return raw == null ? null : api2wire_String(raw);
  }

  @protected
  List<dynamic> api2wire_port_bytes_to_read(PortBytesToRead raw) {
    return [api2wire_String(raw.id), api2wire_PortBytesToReadSender(raw.ready)];
  }

  @protected
  List<dynamic> api2wire_port_desc(PortDesc raw) {
    return [
      api2wire_String(raw.id),
      api2wire_u16(raw.vid),
      api2wire_u16(raw.pid)
    ];
  }

  @protected
  List<dynamic> api2wire_port_open(PortOpen raw) {
    return [
      api2wire_String(raw.id),
      api2wire_u32(raw.baudRate),
      api2wire_PortOpenSender(raw.ready)
    ];
  }

  @protected
  List<dynamic> api2wire_port_read(PortRead raw) {
    return [
      api2wire_String(raw.id),
      api2wire_usize(raw.len),
      api2wire_PortReadSender(raw.ready)
    ];
  }

  @protected
  List<dynamic> api2wire_port_write(PortWrite raw) {
    return [
      api2wire_String(raw.id),
      api2wire_uint_8_list(raw.bytes),
      api2wire_PortWriteSender(raw.ready)
    ];
  }

  @protected
  Uint8List api2wire_u8_array_33(U8Array33 raw) {
    return Uint8List.fromList(raw);
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }

// Section: finalizer

  late final Finalizer<PlatformPointer> _FfiCoordinatorFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_FfiCoordinator);
  Finalizer<PlatformPointer> get FfiCoordinatorFinalizer =>
      _FfiCoordinatorFinalizer;
  late final Finalizer<PlatformPointer> _PortBytesToReadSenderFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_PortBytesToReadSender);
  Finalizer<PlatformPointer> get PortBytesToReadSenderFinalizer =>
      _PortBytesToReadSenderFinalizer;
  late final Finalizer<PlatformPointer> _PortOpenSenderFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_PortOpenSender);
  Finalizer<PlatformPointer> get PortOpenSenderFinalizer =>
      _PortOpenSenderFinalizer;
  late final Finalizer<PlatformPointer> _PortReadSenderFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_PortReadSender);
  Finalizer<PlatformPointer> get PortReadSenderFinalizer =>
      _PortReadSenderFinalizer;
  late final Finalizer<PlatformPointer> _PortWriteSenderFinalizer =
      Finalizer<PlatformPointer>(inner.drop_opaque_PortWriteSender);
  Finalizer<PlatformPointer> get PortWriteSenderFinalizer =>
      _PortWriteSenderFinalizer;
}

// Section: WASM wire module

@JS('wasm_bindgen')
external NativeWasmModule get wasmModule;

@JS()
@anonymous
class NativeWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external NativeWasmModule bind(dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_sub_port_events(NativePortType port_);

  external dynamic /* void */ wire_sub_device_events(NativePortType port_);

  external dynamic /* void */ wire_new_ffi_coordinator(
      NativePortType port_, bool host_handles_serial);

  external dynamic /* void */ wire_turn_stderr_logging_on(
      NativePortType port_, int level);

  external dynamic /* void */ wire_turn_logcat_logging_on(
      NativePortType port_, int _level);

  external dynamic /* void */ wire_announce_available_ports(
      NativePortType port_, Object coordinator, List<dynamic> ports);

  external dynamic /* void */ wire_update_name_preview(
      NativePortType port_, Object coordinator, List<dynamic> id, String name);

  external dynamic /* void */ wire_finish_naming(
      NativePortType port_, Object coordinator, List<dynamic> id, String name);

  external dynamic /* void */ wire_send_cancel(
      NativePortType port_, Object coordinator, List<dynamic> id);

  external dynamic /* void */ wire_generate_new_key(
      NativePortType port_, Object coordinator, int threshold);

  external dynamic /* void */ wire_satisfy__method__PortOpen(
      NativePortType port_, List<dynamic> that, String? err);

  external dynamic /* void */ wire_satisfy__method__PortRead(
      NativePortType port_, List<dynamic> that, Uint8List bytes, String? err);

  external dynamic /* void */ wire_satisfy__method__PortWrite(
      NativePortType port_, List<dynamic> that, String? err);

  external dynamic /* void */ wire_satisfy__method__PortBytesToRead(
      NativePortType port_, List<dynamic> that, int bytes_to_read);

  external dynamic /*  */ drop_opaque_FfiCoordinator(ptr);

  external int /* *const c_void */ share_opaque_FfiCoordinator(ptr);

  external dynamic /*  */ drop_opaque_PortBytesToReadSender(ptr);

  external int /* *const c_void */ share_opaque_PortBytesToReadSender(ptr);

  external dynamic /*  */ drop_opaque_PortOpenSender(ptr);

  external int /* *const c_void */ share_opaque_PortOpenSender(ptr);

  external dynamic /*  */ drop_opaque_PortReadSender(ptr);

  external int /* *const c_void */ share_opaque_PortReadSender(ptr);

  external dynamic /*  */ drop_opaque_PortWriteSender(ptr);

  external int /* *const c_void */ share_opaque_PortWriteSender(ptr);
}

// Section: WASM wire connector

class NativeWire extends FlutterRustBridgeWasmWireBase<NativeWasmModule> {
  NativeWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<NativeWasmModule>(module));

  void wire_sub_port_events(NativePortType port_) =>
      wasmModule.wire_sub_port_events(port_);

  void wire_sub_device_events(NativePortType port_) =>
      wasmModule.wire_sub_device_events(port_);

  void wire_new_ffi_coordinator(
          NativePortType port_, bool host_handles_serial) =>
      wasmModule.wire_new_ffi_coordinator(port_, host_handles_serial);

  void wire_turn_stderr_logging_on(NativePortType port_, int level) =>
      wasmModule.wire_turn_stderr_logging_on(port_, level);

  void wire_turn_logcat_logging_on(NativePortType port_, int _level) =>
      wasmModule.wire_turn_logcat_logging_on(port_, _level);

  void wire_announce_available_ports(
          NativePortType port_, Object coordinator, List<dynamic> ports) =>
      wasmModule.wire_announce_available_ports(port_, coordinator, ports);

  void wire_update_name_preview(NativePortType port_, Object coordinator,
          List<dynamic> id, String name) =>
      wasmModule.wire_update_name_preview(port_, coordinator, id, name);

  void wire_finish_naming(NativePortType port_, Object coordinator,
          List<dynamic> id, String name) =>
      wasmModule.wire_finish_naming(port_, coordinator, id, name);

  void wire_send_cancel(
          NativePortType port_, Object coordinator, List<dynamic> id) =>
      wasmModule.wire_send_cancel(port_, coordinator, id);

  void wire_generate_new_key(
          NativePortType port_, Object coordinator, int threshold) =>
      wasmModule.wire_generate_new_key(port_, coordinator, threshold);

  void wire_satisfy__method__PortOpen(
          NativePortType port_, List<dynamic> that, String? err) =>
      wasmModule.wire_satisfy__method__PortOpen(port_, that, err);

  void wire_satisfy__method__PortRead(NativePortType port_, List<dynamic> that,
          Uint8List bytes, String? err) =>
      wasmModule.wire_satisfy__method__PortRead(port_, that, bytes, err);

  void wire_satisfy__method__PortWrite(
          NativePortType port_, List<dynamic> that, String? err) =>
      wasmModule.wire_satisfy__method__PortWrite(port_, that, err);

  void wire_satisfy__method__PortBytesToRead(
          NativePortType port_, List<dynamic> that, int bytes_to_read) =>
      wasmModule.wire_satisfy__method__PortBytesToRead(
          port_, that, bytes_to_read);

  dynamic /*  */ drop_opaque_FfiCoordinator(ptr) =>
      wasmModule.drop_opaque_FfiCoordinator(ptr);

  int /* *const c_void */ share_opaque_FfiCoordinator(ptr) =>
      wasmModule.share_opaque_FfiCoordinator(ptr);

  dynamic /*  */ drop_opaque_PortBytesToReadSender(ptr) =>
      wasmModule.drop_opaque_PortBytesToReadSender(ptr);

  int /* *const c_void */ share_opaque_PortBytesToReadSender(ptr) =>
      wasmModule.share_opaque_PortBytesToReadSender(ptr);

  dynamic /*  */ drop_opaque_PortOpenSender(ptr) =>
      wasmModule.drop_opaque_PortOpenSender(ptr);

  int /* *const c_void */ share_opaque_PortOpenSender(ptr) =>
      wasmModule.share_opaque_PortOpenSender(ptr);

  dynamic /*  */ drop_opaque_PortReadSender(ptr) =>
      wasmModule.drop_opaque_PortReadSender(ptr);

  int /* *const c_void */ share_opaque_PortReadSender(ptr) =>
      wasmModule.share_opaque_PortReadSender(ptr);

  dynamic /*  */ drop_opaque_PortWriteSender(ptr) =>
      wasmModule.drop_opaque_PortWriteSender(ptr);

  int /* *const c_void */ share_opaque_PortWriteSender(ptr) =>
      wasmModule.share_opaque_PortWriteSender(ptr);
}
