// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:collection/collection.dart';

part 'bridge_definitions.freezed.dart';

abstract class Native {
  Stream<PortEvent> subPortEvents({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSubPortEventsConstMeta;

  Stream<List<DeviceChange>> subDeviceEvents({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSubDeviceEventsConstMeta;

  Stream<KeyState> subKeyEvents({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSubKeyEventsConstMeta;

  Future<void> turnStderrLoggingOn({required Level level, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kTurnStderrLoggingOnConstMeta;

  Future<void> turnLogcatLoggingOn({required Level level, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kTurnLogcatLoggingOnConstMeta;

  Future<void> announceAvailablePorts(
      {required List<PortDesc> ports, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAnnounceAvailablePortsConstMeta;

  Future<void> switchToHostHandlesSerial({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSwitchToHostHandlesSerialConstMeta;

  Future<void> updateNamePreview(
      {required DeviceId id, required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kUpdateNamePreviewConstMeta;

  Future<void> finishNaming(
      {required DeviceId id, required String name, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kFinishNamingConstMeta;

  Future<void> sendCancel({required DeviceId id, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSendCancelConstMeta;

  Future<void> cancelAll({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCancelAllConstMeta;

  Future<List<DeviceId>> registeredDevices({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRegisteredDevicesConstMeta;

  Future<void> startCoordinatorThread({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kStartCoordinatorThreadConstMeta;

  KeyState keyState({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kKeyStateConstMeta;

  Stream<CoordinatorToUserKeyGenMessage> generateNewKey(
      {required int threshold, required List<DeviceId> devices, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGenerateNewKeyConstMeta;

  int thresholdMethodFrostKey({required FrostKey that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kThresholdMethodFrostKeyConstMeta;

  KeyId idMethodFrostKey({required FrostKey that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIdMethodFrostKeyConstMeta;

  String nameMethodFrostKey({required FrostKey that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNameMethodFrostKeyConstMeta;

  Future<void> satisfyMethodPortOpen(
      {required PortOpen that, String? err, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSatisfyMethodPortOpenConstMeta;

  Future<void> satisfyMethodPortRead(
      {required PortRead that,
      required Uint8List bytes,
      String? err,
      dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSatisfyMethodPortReadConstMeta;

  Future<void> satisfyMethodPortWrite(
      {required PortWrite that, String? err, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSatisfyMethodPortWriteConstMeta;

  Future<void> satisfyMethodPortBytesToRead(
      {required PortBytesToRead that, required int bytesToRead, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSatisfyMethodPortBytesToReadConstMeta;

  DropFnType get dropOpaqueFrostsnapCoreSchnorrFunFrostFrostKeyNormal;
  ShareFnType get shareOpaqueFrostsnapCoreSchnorrFunFrostFrostKeyNormal;
  OpaqueTypeFinalizer get FrostsnapCoreSchnorrFunFrostFrostKeyNormalFinalizer;

  DropFnType get dropOpaquePortBytesToReadSender;
  ShareFnType get shareOpaquePortBytesToReadSender;
  OpaqueTypeFinalizer get PortBytesToReadSenderFinalizer;

  DropFnType get dropOpaquePortOpenSender;
  ShareFnType get shareOpaquePortOpenSender;
  OpaqueTypeFinalizer get PortOpenSenderFinalizer;

  DropFnType get dropOpaquePortReadSender;
  ShareFnType get shareOpaquePortReadSender;
  OpaqueTypeFinalizer get PortReadSenderFinalizer;

  DropFnType get dropOpaquePortWriteSender;
  ShareFnType get shareOpaquePortWriteSender;
  OpaqueTypeFinalizer get PortWriteSenderFinalizer;
}

@sealed
class FrostsnapCoreSchnorrFunFrostFrostKeyNormal extends FrbOpaque {
  final Native bridge;
  FrostsnapCoreSchnorrFunFrostFrostKeyNormal.fromRaw(
      int ptr, int size, this.bridge)
      : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn =>
      bridge.dropOpaqueFrostsnapCoreSchnorrFunFrostFrostKeyNormal;

  @override
  ShareFnType get shareFn =>
      bridge.shareOpaqueFrostsnapCoreSchnorrFunFrostFrostKeyNormal;

  @override
  OpaqueTypeFinalizer get staticFinalizer =>
      bridge.FrostsnapCoreSchnorrFunFrostFrostKeyNormalFinalizer;
}

@sealed
class PortBytesToReadSender extends FrbOpaque {
  final Native bridge;
  PortBytesToReadSender.fromRaw(int ptr, int size, this.bridge)
      : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaquePortBytesToReadSender;

  @override
  ShareFnType get shareFn => bridge.shareOpaquePortBytesToReadSender;

  @override
  OpaqueTypeFinalizer get staticFinalizer =>
      bridge.PortBytesToReadSenderFinalizer;
}

@sealed
class PortOpenSender extends FrbOpaque {
  final Native bridge;
  PortOpenSender.fromRaw(int ptr, int size, this.bridge)
      : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaquePortOpenSender;

  @override
  ShareFnType get shareFn => bridge.shareOpaquePortOpenSender;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.PortOpenSenderFinalizer;
}

@sealed
class PortReadSender extends FrbOpaque {
  final Native bridge;
  PortReadSender.fromRaw(int ptr, int size, this.bridge)
      : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaquePortReadSender;

  @override
  ShareFnType get shareFn => bridge.shareOpaquePortReadSender;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.PortReadSenderFinalizer;
}

@sealed
class PortWriteSender extends FrbOpaque {
  final Native bridge;
  PortWriteSender.fromRaw(int ptr, int size, this.bridge)
      : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaquePortWriteSender;

  @override
  ShareFnType get shareFn => bridge.shareOpaquePortWriteSender;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.PortWriteSenderFinalizer;
}

@freezed
sealed class CoordinatorToUserKeyGenMessage
    with _$CoordinatorToUserKeyGenMessage {
  const factory CoordinatorToUserKeyGenMessage.receivedShares({
    required DeviceId id,
  }) = CoordinatorToUserKeyGenMessage_ReceivedShares;
  const factory CoordinatorToUserKeyGenMessage.checkKeyGen({
    required U8Array32 sessionHash,
  }) = CoordinatorToUserKeyGenMessage_CheckKeyGen;
  const factory CoordinatorToUserKeyGenMessage.keyGenAck({
    required DeviceId id,
  }) = CoordinatorToUserKeyGenMessage_KeyGenAck;
  const factory CoordinatorToUserKeyGenMessage.finishedKey({
    required KeyId keyId,
  }) = CoordinatorToUserKeyGenMessage_FinishedKey;
}

@freezed
sealed class DeviceChange with _$DeviceChange {
  const factory DeviceChange.added({
    required DeviceId id,
  }) = DeviceChange_Added;
  const factory DeviceChange.renamed({
    required DeviceId id,
    required String oldName,
    required String newName,
  }) = DeviceChange_Renamed;
  const factory DeviceChange.needsName({
    required DeviceId id,
  }) = DeviceChange_NeedsName;
  const factory DeviceChange.registered({
    required DeviceId id,
    required String name,
  }) = DeviceChange_Registered;
  const factory DeviceChange.disconnected({
    required DeviceId id,
  }) = DeviceChange_Disconnected;
}

class DeviceId {
  final U8Array33 field0;

  const DeviceId({
    required this.field0,
  });
}

class FrostKey {
  final Native bridge;
  final FrostsnapCoreSchnorrFunFrostFrostKeyNormal field0;

  const FrostKey({
    required this.bridge,
    required this.field0,
  });

  int threshold({dynamic hint}) => bridge.thresholdMethodFrostKey(
        that: this,
      );

  KeyId id({dynamic hint}) => bridge.idMethodFrostKey(
        that: this,
      );

  String name({dynamic hint}) => bridge.nameMethodFrostKey(
        that: this,
      );
}

class KeyId {
  final U8Array32 field0;

  const KeyId({
    required this.field0,
  });
}

class KeyState {
  final List<FrostKey> keys;

  const KeyState({
    required this.keys,
  });
}

enum Level {
  Debug,
  Info,
}

class PortBytesToRead {
  final Native bridge;
  final String id;
  final PortBytesToReadSender ready;

  const PortBytesToRead({
    required this.bridge,
    required this.id,
    required this.ready,
  });

  Future<void> satisfy({required int bytesToRead, dynamic hint}) =>
      bridge.satisfyMethodPortBytesToRead(
        that: this,
        bytesToRead: bytesToRead,
      );
}

class PortDesc {
  final String id;
  final int vid;
  final int pid;

  const PortDesc({
    required this.id,
    required this.vid,
    required this.pid,
  });
}

@freezed
sealed class PortEvent with _$PortEvent {
  const factory PortEvent.open({
    required PortOpen request,
  }) = PortEvent_Open;
  const factory PortEvent.write({
    required PortWrite request,
  }) = PortEvent_Write;
  const factory PortEvent.read({
    required PortRead request,
  }) = PortEvent_Read;
  const factory PortEvent.bytesToRead({
    required PortBytesToRead request,
  }) = PortEvent_BytesToRead;
}

class PortOpen {
  final Native bridge;
  final String id;
  final int baudRate;
  final PortOpenSender ready;

  const PortOpen({
    required this.bridge,
    required this.id,
    required this.baudRate,
    required this.ready,
  });

  Future<void> satisfy({String? err, dynamic hint}) =>
      bridge.satisfyMethodPortOpen(
        that: this,
        err: err,
      );
}

class PortRead {
  final Native bridge;
  final String id;
  final int len;
  final PortReadSender ready;

  const PortRead({
    required this.bridge,
    required this.id,
    required this.len,
    required this.ready,
  });

  Future<void> satisfy({required Uint8List bytes, String? err, dynamic hint}) =>
      bridge.satisfyMethodPortRead(
        that: this,
        bytes: bytes,
        err: err,
      );
}

class PortWrite {
  final Native bridge;
  final String id;
  final Uint8List bytes;
  final PortWriteSender ready;

  const PortWrite({
    required this.bridge,
    required this.id,
    required this.bytes,
    required this.ready,
  });

  Future<void> satisfy({String? err, dynamic hint}) =>
      bridge.satisfyMethodPortWrite(
        that: this,
        err: err,
      );
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;
  U8Array32(Uint8List inner)
      : assert(inner.length == arraySize),
        super(inner);
  U8Array32.unchecked(Uint8List inner) : super(inner);
  U8Array32.init() : super(Uint8List(arraySize));
}

class U8Array33 extends NonGrowableListView<int> {
  static const arraySize = 33;
  U8Array33(Uint8List inner)
      : assert(inner.length == arraySize),
        super(inner);
  U8Array33.unchecked(Uint8List inner) : super(inner);
  U8Array33.init() : super(Uint8List(arraySize));
}
