[package]
name = "frostsnap_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256kfun = { workspace = true, default-features = false }
sha2 = { workspace = true, default-features = false }

[dev-dependencies]
