/// Shared test vectors for a 3-of-5 scheme
/// Secret used: 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
/// Generated with fingerprint: 18-bit "frost-v0"
pub const TEST_SHARES_3_OF_5: &[&str] = &[
    "#1 MISS DRAFT FOLD BRIGHT HURRY CONCERT SOURCE CLUB EQUIP ELEGANT TOY LYRICS CAR CABIN SYRUP LECTURE TEAM EQUIP WET ECHO LINK SILVER PURCHASE LECTURE NEXT",
    "#2 CLAW MYSELF SWING VOTE ARTEFACT RITUAL LADY AUGUST ROOKIE MATH DECIDE RIB PROOF ACQUIRE WINE CAPITAL ABUSE GALLERY DECIDE JAZZ TRASH SMART EYEBROW BRONZE SALUTE",
    "#3 RECEIVE GAP DOLPHIN ENLIST RECYCLE BREAD LENS GENRE DISAGREE RIFLE GROUP JEWEL CRISP VITAL REPEAT POLAR SHOP NEXT FRUIT SORT WILD LAPTOP TRY THUNDER ALCOHOL",
    "#4 CLAY POST MASS BRAIN GOOD EYEBROW SWALLOW CANOE STEEL SUNSET IDLE SHRUG GLASS BREAD SUGAR DIARY UPHOLD CREDIT LEGAL STAGE CARPET PICTURE HOUR SHED MOSQUITO",
    "#5 MIX HUB REBUILD GREAT BURDEN FOX MINIMUM EXTEND LEAVE TRIM FILE PEAR MOON FALSE NOW REMIND RIGHT VIOLIN MAN YOU WEB JOKE TRIBE WHERE REGION"
];
