#![allow(unused)]
/// Shared test vectors for a 1-of-1 scheme
/// Secret used: 0x0101010101010101010101010101010101010101010101010101010101010101
/// Generated with fingerprint: 18-bit "frost-v0"
pub const TEST_SHARES_1_OF_1: &[&str] = &[
    "#1 ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CAGE ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CAGE ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CURTAIN SOON",
];

/// The same 1-of-1 secret as a `#0` backup
/// Secret used: 0x0101010101010101010101010101010101010101010101010101010101010101
pub const TEST_SECRET_BACKUP: &str = "#0 ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CAGE ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CAGE ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CHECK WIDTH";

/// Shared test vectors for a 2-of-3 scheme
/// Secret used: 0x0101010101010101010101010101010101010101010101010101010101010101
/// Generated with fingerprint: 18-bit "frost-v0"
pub const TEST_SHARES_2_OF_3: &[&str] = &[
    "#1 MUTUAL JEANS SNAP STING BLESS JOURNEY MORAL BREAD ROOM LIMIT DOSE GRAVITY SORT DELIVER OUTDOOR RIPPLE DONKEY BLOUSE PLAY CART CENTURY MAXIMUM MAKE LOCAL MOBILE",
    "#2 CASH TRASH FOIL PREFER BUTTER IDEA BRAVE BITTER ITEM WINK DRIFT SMILE TOMATO LUNCH OPTION HERO THREE ENGINE BLESS MANAGE HORSE JAR ADVICE SHERIFF BUSINESS",
    "#3 REGION FINISH TRAVEL LAUNDRY CHEAP HAIR PLUNGE BANANA CRACK INTEREST DURING COTTON PHONE DISAGREE CRUNCH AIRPORT CANCEL FOLD LAUNDRY PONY LOBSTER LENS MAMMAL CLOTH FINGER",
];

/// Shared test vectors for a 3-of-5 scheme
/// Secret used: 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
/// Generated with fingerprint: 18-bit "frost-v0"
pub const TEST_SHARES_3_OF_5: &[&str] = &[
    "#1 DUTCH GLAD TORCH EXACT PROGRAM GRASS CLUB SCRAP MUSCLE TUITION TISSUE CLERK SEA SUMMER SHIP VERY FREQUENT DIAL SYRUP MAMMAL SIMILAR MISERY PLAY RING ARM",
    "#2 SUGAR GENERAL PARK VOYAGE CREEK FLY MOTOR ALWAYS WAVE SUNNY WARRIOR DIAMOND WAVE SUNSET ANY LEFT LIGHT FLOAT VAULT GENUINE ELBOW TENNIS BECOME TABLE CLAIM",
    "#3 ORANGE HAMMER UNFOLD REFUSE IMMUNE FAVORITE POET MEDIA CARRY SEGMENT PULL BRUSH DAMAGE ADDRESS FILE PORTION UNFOLD BLAST ACCOUNT NATION TELL BELT DENY ABILITY FOOD",
    "#4 MIRACLE KETCHUP SLIM MAZE GUESS FEBRUARY IDLE ENDORSE BARELY POLAR AGAIN SIBLING CLARIFY SHELL EAGER FISCAL DISTANCE FEW ABOVE SURE FRAME ENFORCE BUTTER MORNING ZOO",
    "#5 PUMPKIN NEUTRAL DESTROY INSTALL BEHAVE FOLD UNDER EAST SHORT MAGNET WORLD DEVICE SPECIAL BUYER STONE MILLION JUNIOR BEAN UPON CRYSTAL SCENE LEARN SEARCH GALAXY SUMMER"
];

/// Shared test vectors for a 4-of-4 scheme
/// Secret used: 0x0202020202020202020202020202020202020202020202020202020202020202
/// Generated with fingerprint: 18-bit "frost-v0"; only A_1 and A_2 are ground (36-bit cap)
pub const TEST_SHARES_4_OF_4: &[&str] = &[
    "#1 CAT WITNESS MARINE SAVE SHOCK DEVELOP CHAOS DEVELOP SMOOTH SELECT RUG FATIGUE CITIZEN OBSCURE DINOSAUR ROOF ACTOR ALCOHOL SCREEN DEMAND PATH DOLPHIN FATIGUE INSECT FORCE",
    "#2 ARTWORK REUNION SECOND TURKEY COMMON CONNECT EQUIP HOTEL AFFORD CLOCK SHRIMP OCTOBER OBJECT SHIELD JEALOUS OBVIOUS ARMOR BURDEN HABIT SHIP EYE WORTH TOP OBJECT BEGIN",
    "#3 TRULY REPAIR WHEAT BRIDGE CANYON STUMBLE DRAMA EDGE GORILLA GROUP MANAGE ORANGE RACCOON VOICE BITTER MARKET ISSUE JOURNEY DELIVER TURN MEDAL MAN SPIRIT WEIRD REFORM",
    "#4 TOMATO HELP WEAR TUNNEL HEAD CRUISE SPAWN CUSTOM PRETTY NEITHER TONE CLOG RELIEF ELSE QUARTER LEND ROBOT OBVIOUS BUS REGION DILEMMA SUCCESS CARRY INJECT BOARD",
];

/// Invalid set for testing fingerprint validation: a 2-of-2 whose polynomial
/// was never ground, so every checksum passes but the fingerprint does not
/// Secret used: 0x0303030303030303030303030303030303030303030303030303030303030303
pub const INVALID_SET_NO_FINGERPRINT: &[&str] = &[
    "#1 ALPHA DEAL SCRUB ASTHMA IDEA LOGIC BRIGHT THOUGHT ALPHA DEAL SCRUB ASTHMA IDEA LOGIC BRIGHT THOUGHT ALPHA DEAL SCRUB ASTHMA IDEA LOGIC BRIGHT WINDOW BARELY",
    "#2 ARCH FLAME SECURITY BID RADAR MACHINE CLUB GESTURE ARCH FLAME SECURITY BID RADAR MACHINE CLUB GESTURE ARCH FLAME SECURITY BID RADAR MACHINE CLUB GLOOM INFORM",
];

/// Invalid share for testing checksum validation
/// This is TEST_SHARES_2_OF_3[0] with the last word changed from "MOBILE" to "ABANDON"
pub const INVALID_SHARE_CHECKSUM: &str = "#1 MUTUAL JEANS SNAP STING BLESS JOURNEY MORAL BREAD ROOM LIMIT DOSE GRAVITY SORT DELIVER OUTDOOR RIPPLE DONKEY BLOUSE PLAY CART CENTURY MAXIMUM MAKE LOCAL ABANDON";

/// Invalid share for testing scalar range validation
/// This encodes the group order N itself, with a polynomial checksum of 0 and a valid words checksum
pub const INVALID_SHARE_SCALAR: &str = "#1 ZOO ZOO ZOO ZOO ZOO ZOO ZOO ZOO ZOO ZOO ZOO WORD PRIORITY HOVER ONE TROUBLE PARENT TARGET VIRUS RUG SNACK BRASS AGREE CACTUS MIRACLE";

/// Invalid share for testing polynomial checksum validation
/// This is TEST_SHARES_2_OF_3[0] with every bit of its polynomial checksum flipped and the last word recomputed
pub const INVALID_SHARE_POLY_CHECKSUM: &str = "#1 MUTUAL JEANS SNAP STING BLESS JOURNEY MORAL BREAD ROOM LIMIT DOSE GRAVITY SORT DELIVER OUTDOOR RIPPLE DONKEY BLOUSE PLAY CART CENTURY MAXIMUM MAKE ORIGINAL IMPULSE";

/// Invalid `#0` backup for testing polynomial checksum validation
/// This is TEST_SECRET_BACKUP with every bit of its polynomial checksum flipped and the last word recomputed
pub const INVALID_SECRET_BACKUP_POLY_CHECKSUM: &str = "#0 ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CAGE ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE CAGE ABSURD AMOUNT DOCTOR ACOUSTIC AVOID LETTER ADVICE DECLINE SILK";
