use crate::{bobbing_carat::BobbingCarat, gray4_style::Gray4TextStyle, Column, SizedBox, Text};
use alloc::string::ToString;
use embedded_graphics::{geometry::Size, pixelcolor::Rgb565};
use frostsnap_fonts::NOTO_SANS_14_LIGHT;
use frostsnap_macros::Widget;

// Font constant for swipe up text - using smaller 14pt font for better fit with chevron
const FONT_SWIPE_UP: &frostsnap_fonts::Gray4Font = &NOTO_SANS_14_LIGHT;

/// SwipeUpChevron that uses Gray4 fonts
/// Includes a bottom spacer to push the text away from screen edge
/// Uses smaller 16px chevron icon for better proportions
#[derive(Widget)]
pub struct SwipeUpChevron {
    #[widget_delegate]
    column: Column<(BobbingCarat, Text<Gray4TextStyle>, SizedBox<Rgb565>)>,
}

impl SwipeUpChevron {
    pub fn new(color: Rgb565, background_color: Rgb565) -> Self {
        // Create smaller bobbing carat (16px size)
        let bobbing_carat = BobbingCarat::new(color, background_color);

        // Create text with smaller Gray4 font (14pt) - works better with smaller chevron
        let text = Text::new(
            "Swipe up".to_string(),
            Gray4TextStyle::new(FONT_SWIPE_UP, color),
        );

        // Add 8px spacing beneath the text to push it away from screen edge
        let bottom_spacer = SizedBox::<Rgb565>::new(Size::new(1, 8));

        // Create column with chevron, text, and spacer beneath text
        let column = Column::new((bobbing_carat, text, bottom_spacer));

        Self { column }
    }
}

// All trait implementations are now generated by the derive macro
