name: "App build preamble"
description: "Sets up common stuff for building the flutter app"

runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@just
    - uses: dtolnay/rust-toolchain@stable
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    - uses: "./.github/actions/fetch-cargo-deps"
    - uses: "./.github/actions/fetch-dart-deps"
    - uses: "./.github/actions/generate-frb"
    - uses: "./.github/actions/install-cargo-bins" # needed for espflash
    - name: Download signed firmware
      shell: bash
      run: |
        mkdir -p target/riscv32imc-unknown-none-elf/release
        curl -L -o target/riscv32imc-unknown-none-elf/release/firmware.bin \
          "https://github.com/frostsnap/frostsnap/releases/download/v0.0.1/firmware.bin"
