default: gen lint

gen:
    flutter_rust_bridge_codegen \
        --rust-input native/src/api.rs \
        --dart-output lib/bridge_generated.dart \
        --c-output ios/Runner/bridge_generated.h \
        --extra-c-output-path macos/Runner/ \
        --dart-decl-output lib/bridge_definitions.dart \
        --wasm

build TARGET="linux" +ARGS="":
    flutter build {{TARGET}} {{ARGS}}

run +ARGS="":
    flutter run {{ARGS}}

lint:
    cd native && cargo fmt
    dart format .

clean:
    flutter clean
    cd native && cargo clean

flutter_rust_bridge_version:
    #!/bin/sh
    flutter_rust_bridge_version=$(perl -0777 -nE '/name = "flutter_rust_bridge".*?version = "(.*?)"/s && print $1' < ../Cargo.lock)
    echo $flutter_rust_bridge_version

install-flutter-deps:
    #!/bin/sh
    flutter pub get

install-cargo-bins:
    #!/bin/sh
    flutter_rust_bridge_version=$(just flutter_rust_bridge_version)
    if ! test "$flutter_rust_bridge_version"; then
        echo "couldn't determine version for flutter_rust_bridge" >&2;
        exit 1
    fi
    cargo install cargo-ndk@3.5.4 espflash@3.2.0 cargo-expand@1.0.95 "flutter_rust_bridge_codegen@$flutter_rust_bridge_version"

serve *args='':
    flutter pub run flutter_rust_bridge:serve {{args}}

build-appimage +ARGS="":
    appimage-builder --recipe AppImageBuilder.yml {{ARGS}}

# vim:expandtab:sw=4:ts=4
