name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  device:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["v2"]
    defaults:
      run:
        working-directory: ./device
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@just
      - name: Cache RISC-V GCC
        uses: actions/cache@v3
        with:
          path: ${GITHUB_WORKSPACE}/device/riscv
          key: ${{ runner.os }}-riscv-gcc-${{ hashFiles('**/riscv-gcc-version.txt') }}
      - name: Setup | RISC-V GCC prerequisites
        run: sudo apt-get update && sudo apt-get install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build
      - name: Setup | RISCV GCC
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        run: |
          wget -nv https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.05.24/riscv32-elf-ubuntu-22.04-nightly-2023.05.24-nightly.tar.gz
          tar -zxf riscv32-elf-ubuntu-22.04-nightly-2023.05.24-nightly.tar.gz
          echo "PATH=$PATH:${GITHUB_WORKSPACE}/device/riscv/bin" >> $GITHUB_ENV
          ls ${GITHUB_WORKSPACE}/device/riscv/bin
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imc-unknown-none-elf
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: just lint-device --release
      - run: just build-device ${{ matrix.board }}
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: frostsnap-${{ github.sha }}.elf
          path: target/riscv32imc-unknown-none-elf/release/v2
          if-no-files-found: error

  non-device:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: just frostsnapp/install-rust-deps
      - run: just lint-non-device --release
      - run: just test --release --all-features

  app-build:
    needs: device
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_command: linux
            artifact_name: Frostsnapp-${{ github.sha }}-x86_64.AppImage
            artifact_path: Frostsnapp.AppImage
          - os: windows-latest
            build_command: windows
            artifact_name: Frostsnapp-${{ github.sha }}-windows-x64
            artifact_path: frostsnapp/build/windows/x64/runner/Release
          - os: macos-latest
            build_command: macos
            artifact_name: Frostsnapp-${{ github.sha }}-x64.app
            artifact_path: frostsnapp/build/macos/Build/Products/Release/frostsnapp.app
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download firmware elf
        uses: actions/download-artifact@v4
        with:
          name: frostsnap-${{ github.sha }}.elf
          path: target/riscv32imc-unknown-none-elf/release/
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@just
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: Swatinem/rust-cache@v2
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libstdc++-12-dev libgtk-3-0 libgtk-3-dev libudev-dev libarchive-tools qtbase5-dev qt5-qmake qtdeclarative5-dev cmake
      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install just
          sudo gem install cocoapods
      - name: Configure macOS
        if: matrix.os == 'macos-latest'
        run: |
          cd frostsnapp
          flutter pub get
          cd macos
          pod install
          cd ../..
      - run: just frostsnapp/install-rust-deps
      - name: Build app
        run: just frostsnapp/build ${{ matrix.build_command }} --release
      - name: Build AppImage (Linux only)
        if: matrix.os == 'ubuntu-latest'
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: frostsnapp-${{ github.sha }}-x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - name: Prepare AppImage (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo chmod +x Frostsnapp-latest-x86_64.AppImage
          mv Frostsnapp-latest-x86_64.AppImage Frostsnapp.AppImage
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error

  app-build-android:
    runs-on: ubuntu-latest
    needs: device
    steps:
      - uses: actions/checkout@v3
      - name: Download firmware elf
        uses: actions/download-artifact@v4
        with:
          name: frostsnap-${{ github.sha }}.elf
          path: target/riscv32imc-unknown-none-elf/release/
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
      - uses: taiki-e/install-action@just
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          cache: gradle
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: just frostsnapp/install-rust-deps
      - run: just frostsnapp/build apk --release
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: frostsnap-${{ github.sha }}.apk
          path: frostsnapp/build/app/outputs/apk/release/app-release.apk
          if-no-files-found: error
      - run: just frostsnapp/build appbundle --release
      - name: Upload Android App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: frostsnap-${{ github.sha }}.aab
          path: frostsnapp/build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error